---
title: "Data Pipelines"
Author: Bethany Gilson
Date: 2020-04-21
output: html_notebook
---

Data pipelines use the tidyversestyle of doing things (ie with pipes!)

```{r}
library(tidyverse)
```

```{r}
write_csv(iris, "iris.csv")
```

## Read
```{r}
iris_raw = read_csv("iris.csv" )
```

```{r}
library(readxl)
library(writexl)
write_xlsx(iris, "iris.xlsx")
read_excel("iris.xlsx")
```

```{r eval=FALSE}
library(haven)
write_dta(iris, "iris.dta")
read_stata("iris.dta")
```

## Exploratory analysis
Data Explorer

```{r}
DataExplorer::create_report(iris_raw, y="Species")
```

## Querying rows

Top and Tails
```{r}
iris_raw %>% 
  head(10)

iris_raw %>% 
  tail(10)

iris_raw %>%
  sample_n(10)

iris_raw %>%
  sample_frac(0.10)

head(iris_raw, 10)
tail(iris_raw, 10)
sample_n(iris_raw, 10)
sample_frac(iris_raw, 0.10)
```

WHERE

```{r}
iris_raw %>% 
  filter(Species=="setosa", Sepal.Length > 5.5)

filter(iris_raw, Species=="setosa", Sepal.Length > 5.5)
```

```{r}
iris_raw %>% 
  filter(Species=="setosa", 
         Sepal.Length < mean(Sepal.Length)) %>% 
  filter(Sepal.Width<3)

filter(filter(iris_raw, Species=="setosa",
              Sepal.Length < mean(Sepal.Length)),
       Sepal.Width<3)
```

```{r}
iris_raw %>% 
  filter((Species=="setosa" | Sepal.Length > 5.5),
         Sepal.Width < 3)
```

Equal
Less / Greater Than
Not Equal

TRUE
FALSE

```{r}
TRUE & TRUE
TRUE & FALSE

# YELLOW & (BLUE OR RED)
TRUE & (FALSE)
TRUE & TRUE
```

```{r}
iris_raw %>% 
  filter_if(is.numeric, ~ . < 5)

iris_raw %>% 
  filter_if(is.numeric, any_vars( . < 5))

iris_raw %>% 
  filter_if(is.numeric, any_vars( . < 1))
```

